# Generated by Django 4.1.1 on 2022-10-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_fecha_nacimiento_persona_fecha_creacion"),
    ]

    operations = [
        migrations.RenameModel(old_name="Persona", new_name="Humano",),
    ]
