# Generated by Django 4.1.1 on 2022-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_persona_humano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="humano",
            name="fecha_creacion",
            field=models.DateField(null=True),
        ),
    ]
